### ISSUE TITLE
Error at the synteny step when running the example dataset.

### ISSUE THREAD

**Issue by MartinLaforest** [jtlovell/GENESPACE#34]
Hello, 

I have first encountered an error running orthofinder:  Running OrthoFinder algorithm. Below is the transcript. 
        -----------------------------
        2022-09-15 15:47:14 : Initial processing of each species
        Malformatted line in /home/laforestm/Desktop/testGenespace/orthofinder/Results_Sep15/WorkingDirectory/Blast0_0.txt
        Offending line was:

        Process Process-8:
        Traceback (most recent call last):
          File "/home/laforestm/miniconda3/envs/orthofinder/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
            self.run()
          File "/home/laforestm/miniconda3/envs/orthofinder/lib/python3.10/multiprocessing/process.py", line 108, in run
            self._target(*self._args, **self._kwargs)
          File "/home/laforestm/miniconda3/envs/orthofinder/bin/scripts_of/__main__.py", line 529, in Worker_ProcessBlastHits
            WaterfallMethod.ProcessBlastHits(*args, d_pickle=d_pickle, qDoubleBlast=qDoubleBlast)
          File "/home/laforestm/miniconda3/envs/orthofinder/bin/scripts_of/__main__.py", line 516, in ProcessBlastHits
            Bij = blast_file_processor.GetBLAST6Scores(seqsInfo, blastDir_list, seqsInfo.speciesToUse[iSpecies], seqsInfo.speciesToUse[jSpecies], qDoubleBlast=qDoubleBlast)
          File "/home/laforestm/miniconda3/envs/orthofinder/bin/scripts_of/blast_file_processor.py", line 65, in GetBLAST6Scores
            for row in blastreader:
        _csv.Error: line contains NUL
        ERROR: Blast0_0.txt is corrupted
        ERROR: Error processing files Blast0_*
        ERROR: An error occurred, ***please review the error messages*** they may contain useful information about the problem.Warning message:
In system2(p2of, com, stdout = TRUE, stderr = TRUE) :
  running command ''orthofinder' -f /home/laforestm/Desktop/testGenespace/peptide -t 6 -a 1 -X -o ~/Desktop/testGenespace/orthofinder 2>&1' had status 1

This was solved by running orthofinder externally adding the -S blast_gz argument to orthofinder.

But when I run synteny analysis I get the following error. 

> gpar <- synteny(gsParam = gpar)
Parsing the gff files ... 
	Reading the gffs and adding orthofinder IDs ... Error in fread(file.path(path, "SpeciesIDs.txt"), sep = ":", header = F,  : 
  File 'NA/SpeciesIDs.txt' does not exist or is non-readable. getwd()=='/media/2TB/genespace2'

It may be a simple thing but I don't find the answer.

Thanks in advance

Martin

**Comment by jtlovell** [comment]
My guess is you do not have the right version of diamond installed. Make sure it is >2.

**Comment by jtlovell** [comment]
Were you able to resolve this issue? Re-open if not.
