### ISSUE TITLE
ERROR: Blast0_0.txt is corrupted

### ISSUE THREAD

**Issue by Tdanis** [jtlovell/GENESPACE#39]
Hello,

I am trying to run your examples but I get this error (ERROR: Blast0_0.txt is corrupted)

ERROR: Error processing files Blast0_*
	Malformatted line in ...../WorkingDirectory/Blast0_0.txt
	Offending line was:
	
	Process Process-14:
	Traceback (most recent call last):
	  File .../Python/3.8.6/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
	    self.run()
	  File ...//3.8.6/lib/python3.8/multiprocessing/process.py", line 108, in run
	    self._target(*self._args, **self._kwargs)

	  File "/gpfs23/...//__main__.py", line 529, in Worker_ProcessBlastHits
	    WaterfallMethod.ProcessBlastHits(*args, d_pickle=d_pickle, qDoubleBlast=qDoubleBlast)
	  File "/.././__main__.py", line 516, in ProcessBlastHits
	    Bij = blast_file_processor.GetBLAST6Scores(seqsInfo, blastDir_list, seqsInfo.speciesToUse[iSpecies], seqsInfo.speciesToUse[jSpecies], qDoubleBlast=qDoubleBlast)
	  File "/...//blast_file_processor.py", line 65, in GetBLAST6Scores
	    for row in blastreader:
	  File "/...//3.8.6/lib/python3.8/codecs.py", line 322, in decode
	    (result, consumed) = self._buffer_decode(data, self.errors, final)
	UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9f in position 2: invalid start byte
	ERROR: An error occurred, ***please review the error messages*** they may contain useful information about the problem.Warning message:
In system2(p2of, com, stdout = TRUE, stderr = TRUE) :
  running command ''orthofinder' -f /home/tdanis/Desktop/testGenespace/peptide -t 12 -a 1 -X -o ~/Desktop/testGenespace/orthofinder 2>&1' had status 1

Any idea?

**Comment by Tdanis** [comment]
It worked!!! Thank you do much.
